# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: $(majorMinorVersion).$(semanticVersion) # $(rev:r) # NOTE: rev resets when the default retention period expires

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  majorMinorVersion: 1.0
  semanticVersion: $[counter(variables['majorMinorVersion'], 0)]

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      #Get Path to csproj
      $path = "./Spencen.Common.Calendar/Spencen.Common.Calendar.csproj"
      
      echo $path
      
      #Read csproj (XML)
      $xml = [xml](Get-Content $path)
      
      echo $xml
      
      #Retrieve Version Nodes
      $assemblyVersion = $xml.Project.PropertyGroup.Version
      
      echo "Version: $assemblyVersion"
      
      #Split the Version Numbers
      $vMajor, $vMinor, $vBuild  = $assemblyVersion.Split(".")

      $majorMinorVersion = "$vMajor.$vMinor.$vBuild"
      [System.Environment]::SetEnvironmentVariable('majorMinorVersion', $majorMinorVersion, [System.EnvironmentVariableTarget]::User)

      $semanticVersion = [System.Environment]::GetEnvironmentVariable('semanticVersion', [System.EnvironmentVariableTarget]::User)
      echo "Reconstructed Version: $vMajor.$vMinor.$vBuild.$semanticVersion"

      echo '##vso[task.setvariable variable=majorMinorVersion]0.2.4'
      echo "Local: $(majorMinorVersion)"
      echo "Env: $(env:majorMinorVersion)"

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Test.csproj'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/Spencen.Common.Calendar.csproj'
    versioningScheme: 'byBuildNumber'
    includeSymbols: true

- task: NuGetAuthenticate@0

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '9081bce7-2023-4edf-b8a0-42617df8dbbf'
    allowPackageConflicts: false