# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: $(majorMinorVersion).$(semanticVersion) # $(rev:r) # NOTE: rev resets when the default retention period expires

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  majorMinorVersion: 1.0
  semanticVersion: $[counter(variables['majorMinorVersion'], 0)]

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      #Get Path to csproj
      $path = "$PSScriptRoot/Spencen.Common.Calendar/Spencen.Common.Calendar.csproj"
      
      echo $path
      
      #Read csproj (XML)
      $xml = [xml](Get-Content $path)
      
      #Retrieve Version Nodes
      $assemblyVersion = $xml.Project.PropertyGroup.AssemblyVersion
      $fileVersion = $xml.Project.PropertyGroup.FileVersion
      
      echo "Assembly version: $assemblyVersion"
      echo "File version: $fileVersion"

      #Split the Version Numbers
      $avMajor, $avMinor, $avBuild  = $assemblyVersion.Split(".")
      $fvMajor, $fvMinor, $fvBuild = $fileVersion.Split(".")

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Test.csproj'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/Spencen.Common.Calendar.csproj'
    versioningScheme: 'byBuildNumber'
    includeSymbols: true

- task: NuGetAuthenticate@0

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '9081bce7-2023-4edf-b8a0-42617df8dbbf'
    allowPackageConflicts: true